In [1]:
#numpy stand for numercial python 2005 
#work on array its is 50 time  faster than list,continous location,latest CPU architectures
!pip install Numpy

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import numpy
arr=numpy.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [13]:
print(np.__version__)

1.26.4


In [14]:
arr3=np.array([1,3,5,7,9])
print(arr3)
print(type(arr3))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
list= np.array([1,2,3,4,5])
set= np.array({2,4,5,6,7})
tuple= np.array((1,3,5,7,9))
print('list',list,'set',set,'tuple',tuple)
print(type(list))
print(type(set))
print(type(tuple))

list [1 2 3 4 5] set {2, 4, 5, 6, 7} tuple [1 3 5 7 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
# dimensions 0D array
import numpy as np
arr4=np.array(43)
print(arr4)
print(arr4.ndim)
arr5=np.array([[1,2,3,4],[1,2,3,5]])
print(arr5)
print(arr5.ndim)
arr6=np.array([[[1,2,3],[1,2,3],[2,4,5]]])
print(arr6)
print(arr6.ndim)

43
0
[[1 2 3 4]
 [1 2 3 5]]
2
[[[1 2 3]
  [1 2 3]
  [2 4 5]]]
3


In [38]:
arr1=np.array([[[[[1,2,3,4,5],[2,3,4,5,6],[1,2,3,4,5],[2,3,4,5,6],[2,3,4,5,6],[1,1,1,1,1]]]]])
print(arr1)
print(arr1.ndim)

[[[[[1 2 3 4 5]
    [2 3 4 5 6]
    [1 2 3 4 5]
    [2 3 4 5 6]
    [2 3 4 5 6]
    [1 1 1 1 1]]]]]
5


In [41]:
arr4=np.array([1,2,3,4,5])
print(arr4[0])

1


In [49]:
A1=np.array([4,5,6,7,8,9])
print(A1[2:4])
print(A1[3]**2)
print(np.sqrt(A1[4]))

[6 7]
49
2.8284271247461903


In [58]:
arr9 = np.array([[1,2,3,4],[1,2,3,5]])
print("5th element of 2 row ", arr9[1,3])

5th element of 2 row  5


In [63]:
arr9 = np.array([[1,2,3,4],[1,2,3,5]])
print(arr9[0,1:3])
print(arr9[1,2:4])

[2 3]
[3 5]


In [80]:
B1=np.array([[[1,2,3,4,5],[2,2,2,2,2],[4,5,6,7,8]]])
print(B1[0,2,1:4])
print(B1.dtype)


[5 6 7]
int32


In [85]:
B1=np.array([1,2,3,4,5],dtype='S')
print(B1)
print(B1.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [5]:
import numpy as np
B1=np.array([1.2,2.4,3.5,4,5],dtype='i8')
print(B1)
print(B1.dtype)

[1 2 3 4 5]
int64


In [7]:
# !pip install (library name) --upgrade      (command for upgrading library)

In [13]:
# give shape to array
import numpy as np
arr=np.array([[[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]]])
print(arr.shape)
arr1=np.array([1,2,3,4])
print(arr.shape)

(1, 1, 4, 4)
(1, 1, 4, 4)


In [18]:
arr2=np.array([1,2,3,4],ndmin=5)
print(arr2)
print("The shape of array is:",arr2.shape)

[[[[[1 2 3 4]]]]]
The shape of array is: (1, 1, 1, 1, 4)


In [25]:
# reshaping of array
Q=np.array([1,2,3,4,5,6])
new_Q=Q.reshape(2,3)
print(new_Q)

[[1 2 3]
 [4 5 6]]


In [26]:
R=np.array([1,2,3,4,5,6,7,8])
print(R.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [28]:
#iterating array 1D array
Y=np.array([1,2,3,4])
for x in Y:
    print(x)

1
2
3
4


In [32]:
#2D array
arr3=np.array([[[1,2,3,4],[5,6,7,8],[5,5,5,5]]])
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
5
5
5
5


In [34]:
#concatenate is used for two array
A1=np.array([1,2,3])
A2=np.array([4,5,6])
C1=np.concatenate((A1,A2))
print(C1)
C2=A1+A2
print(C2)

[1 2 3 4 5 6]
[5 7 9]


In [39]:
R1=np.array([[1,2],[3,4]])
R2=np.array([[5,6],[7,8]])
R3=np.concatenate((R1,R2),axis=1)
print(R3)
R1_new = np.expand_dims(R1, axis=2)
R2_new = np.expand_dims(R2, axis=2)
R4 = np.concatenate((R1_new, R2_new), axis=2)
print(R4)

[[1 2 5 6]
 [3 4 7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [41]:
# for splitting array  we use (array_split) command
R5=np.array([1,2,3,4,5])
newR=np.array_split(R5,6)
print(newR)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([], dtype=int32)]


In [43]:
arr9=np.array([1,2,3,4,5,4,4,4])
x=np.where(arr9==4)
print(x)
x2=np.where(arr9==6)
print(x2)

(array([3, 5, 6, 7], dtype=int64),)
(array([], dtype=int64),)


In [48]:
Q1=np.array([1,2,3,4,5,6,7,8])
x5=np.where(Q1%2!=0)
print(x5)

(array([0, 2, 4, 6], dtype=int64),)


In [51]:
Q1=np.array([1,2,3,4,5,6,7,8])
print(np.sort(Q1)[::-1])

[8 7 6 5 4 3 2 1]


In [53]:
Q1=np.array([1,2,4,3,4,5,4,4,4])
print(np.sort(Q1)[::-1])

[5 4 4 4 4 4 3 2 1]


In [55]:
Q7=np.array(['banana','cherry','apple'])
x6=np.sort(Q7)
print(x6)

['apple' 'banana' 'cherry']


In [59]:
# filtering array
Q9=np.array([41,42,43,44])
x4=[True,True,False,True]
new_Q9=Q9[x4]
print(new_Q9)

[41 42 44]


In [64]:
Q10=np.array([1,2,3,4,5,6,7,8,9])
x7=Q10 % 2 == 0
print(x7)   

[False  True False  True False  True False  True False]
